# Generated by Django 5.0.1 on 2024-01-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='uploads/')),
                ('certificate2', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('MK', 'MK'), ('DS', 'DS'), ('SF', 'SF'), ('FS', 'FS'), ('BD', 'BD'), ('FD', 'FD'), ('CS', 'CS'), ('3D', '3D'), ('NA', 'NA')], max_length=2)),
                ('ID_category', models.CharField(max_length=300)),
            ],
        ),
    ]
