# Generated by Django 5.0.1 on 2024-01-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(default='<django.db.models.fields.CharField>+astrum')),
            ],
        ),
    ]
