# Generated by Django 5.0.1 on 2024-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
