# Generated by Django 5.0.1 on 2024-01-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_certificate_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='category',
            new_name='seria',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='ID_category',
            new_name='sertificate_id',
        ),
    ]
